# Generated by Django 2.2.3 on 2019-07-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('table_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start reservation time')),
                ('end_time', models.DateTimeField(verbose_name='end reservation time')),
                ('number_of_person', models.IntegerField()),
                ('comment', models.CharField(max_length=300)),
                ('reservation_name', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_reservation.Table')),
            ],
        ),
    ]
